version: "3"
services:
    main:
        container_name: "teagram"
        build:
            context: .
        volumes:
            - main:/data
        stop_signal: SIGINT
        restart: on-failure
        command: python3 -m teagram

volumes:
    main:
